server:
  port: 8090
  context-path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3308/mlg
    username: root
    password: koreait

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.gg.mlg
