server:
  port: 8090
  context-path: /

spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mlg.ckhnav7yzn73.ap-northeast-2.rds.amazonaws.com:3306/mlg
    username: admin
    password: koreait1234
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
      location: C:/springImg
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 875512213138-ba6ebnf885brcmhemtn2grdecibg0jig.apps.googleusercontent.com
            client-secret: YSupq_6YerhXzFY3jYwZ-vqz
            scope:
              - profile
              - email
          facebook:
            client-id: 948545875703760
            client-secret: d64ede0326d0bdd5780de677219fc520
          kakao:
            authorization-grant-type: authorization_code
            client-id: fe7e72159bd674c86017d934fb0b3fc2
            client-secret: 0uFb4mKe9lFErUI3j8Ti20XactEKi42O
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile_nickname
            client-authentication-method: POST
            client-name: Kakao
          naver:
            authorization-grant-type: authorization_code
            client-id: AOwg9XAlVtUkcVAxIA3C
            client-secret: Tj2YeTmEtf
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: name
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: properties
            # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
  sendgrid:
    api-key: RGAPI-0c8510fb-a7f1-4a8a-8b2d-e85b6819f9a6

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.gg.mlg